name: ticats
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  auto_mappr_annotation: ^2.1.0
  cached_network_image: ^3.3.0
  calendar_date_picker2: ^0.5.3
  crop_your_image: ^0.7.5
  dio: ^5.4.0
  fl_chart: ^0.66.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_email_sender: ^6.0.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_native_splash: ^2.3.8
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  flutter_toggle_tab: ^1.4.1
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  kakao_flutter_sdk: ^1.7.0
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  retrofit: ^4.0.3
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  sign_in_with_apple: ^5.0.0
  stacked_card_carousel: ^0.0.4

dev_dependencies:
  auto_mappr: ^2.2.0
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/cats/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/terms/
    - assets/tickets/
    - assets/tutorial/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Thin.ttf
          weight: 100
        - asset: assets/fonts/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUIT-Light.ttf
          weight: 300
        - asset: assets/fonts/SUIT-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUIT-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUIT-Heavy.ttf
          weight: 900
