name: ticats
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  fluttertoast: ^8.2.4
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  kakao_flutter_sdk: ^1.7.0
  permission_handler: ^11.1.0
  retrofit: ^4.0.3
  sign_in_with_apple: ^5.0.0

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.5

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/cats/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/terms/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/fonts/SUIT-Thin.ttf
          weight: 100
        - asset: assets/fonts/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SUIT-Light.ttf
          weight: 300
        - asset: assets/fonts/SUIT-Regular.ttf
          weight: 400
        - asset: assets/fonts/SUIT-Medium.ttf
          weight: 500
        - asset: assets/fonts/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SUIT-Bold.ttf
          weight: 700
        - asset: assets/fonts/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/SUIT-Heavy.ttf
          weight: 900
